# Generated by Django 2.2.2 on 2019-06-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mygroup',
            name='point',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='mygroup',
            name='surname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
